Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "10.10.10.20"

  config.vm.synced_folder "roots/", "/srv/salt"

  config.vm.provision :salt do |sa|
    sa.masterless = true
    sa.minion_config = "minionfiles/minion.yml"
    sa.run_highstate = true
  end

end
