Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "10.10.10.12"

  config.vm.provision "shell", :inline => <<-SHELL
      apt-get update
      apt-get install -y puppet
  SHELL

  config.vm.provision "puppet" do |pup|
    pup.manifest_file = "nginx.pp"
  end

end
