Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "10.10.10.10"

  config.vm.provision "chef_solo" do |ch|
    ch.add_recipe "nginx"
  end

end
